version: "3.9"
services:
  meili:
    image: getmeili/meilisearch
    ports:
      - 7700:7700
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: search
  seed:
    build:
      context: .
      args:
          command: seed
    links:
      - meili
      - postgres
    volumes:
      - type: bind
        source: ${PWD}/mirror-extract.json
        target: /data.json
  web:
    build:
      context: .
      args:
          command: serve
    links:
      - meili
      - postgres
    ports:
      - 8080:8080